In [1]:
import numpy as np
x=np.random.randint(0,20,(6,5))
print(x)

[[16 11 17 13 18]
 [ 3  1  5  9 16]
 [18  9 11 12  6]
 [16 16 19 15 12]
 [ 1  7 10  6 14]
 [16 16 12 12  4]]


In [4]:
#ravel returns the flatten the array
x.ravel()

array([16, 11, 17, 13, 18,  3,  1,  5,  9, 16, 18,  9, 11, 12,  6, 16, 16,
       19, 15, 12,  1,  7, 10,  6, 14, 16, 16, 12, 12,  4])

In [5]:
y=x.ravel()

In [6]:
y.reshape(10,3)

array([[16, 11, 17],
       [13, 18,  3],
       [ 1,  5,  9],
       [16, 18,  9],
       [11, 12,  6],
       [16, 16, 19],
       [15, 12,  1],
       [ 7, 10,  6],
       [14, 16, 16],
       [12, 12,  4]])

In [7]:
x1=np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [8]:
x2=np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [9]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [10]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [12]:
np.concatenate([x1,x2],axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [13]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [14]:
d=np.arange(24,dtype='float')
print(d)
print(d.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
float64


In [15]:
#numpy mamethamatical functions
import numpy as np
np.sum([10,30,60,54,68,258])

480

In [18]:
a=[10,20]
b=[20,5]
np.sum([a,b])

55

In [21]:
#addition
import numpy as np
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
sum_array=array1+array2
print(sum_array)
sum_array.ndim

[[ 8 10 12]
 [14 16 18]]


2

In [22]:
#subtraction
a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])
sub=a-b-c
print(sub)

[ 0 -5  1]


In [25]:
#using different shapes (broadcasting)
import numpy as np
a=np.array([[1,2],[6,8],[6,5]])
b=np.array([5,4])
res=a+b
print("result of a+b with broadcasting:\n",res)

result of a+b with broadcasting:
 [[ 6  6]
 [11 12]
 [11  9]]


In [26]:
import numpy as np
a=np.array([[1,2],[6,8],[6,5]])
b=np.array([5,4])
res=a-b
print("result of a-b with broadcasting:\n",res)

result of a-b with broadcasting:
 [[-4 -2]
 [ 1  4]
 [ 1  1]]
